# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - x64 

configuration:
  - Release

# clone directory
clone_folder: C:\projects\cosmo-engine

install:
  # SDL2
  - ps: |
      $SDL_VERSION = "2.0.7"
      $SDL2DIR = "C:\sdl_root\SDL2-$SDL_VERSION"
      if (!(Test-Path -Path $SDL2DIR)) {
        Start-FileDownload https://libsdl.org/release/SDL2-devel-$SDL_VERSION-VC.zip
        7z x SDL2-devel-$SDL_VERSION-VC.zip -aoa -oC:\sdl_root\
      }
      $env:SDL2DIR = $SDL2DIR
  # SDL2_mixer
  - ps: |
      $SDL_MIXER_VERSION = "2.0.2"
      $SDL2MIXERDIR = "C:\sdl_root\SDL2_mixer-$SDL_MIXER_VERSION"
      if (!(Test-Path -Path $SDL2MIXERDIR)) {
        Start-FileDownload https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-$SDL_MIXER_VERSION-VC.zip
        7z x SDL2_mixer-devel-$SDL_MIXER_VERSION-VC.zip -aoa -oC:\sdl_root\
      }
      $env:SDL2MIXERDIR = $SDL2MIXERDIR

# scripts to run before build
before_build:
  - cmd: cd C:\projects\cosmo-engine
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" ..

after_build:
  - cmd: 7z a c:\projects\cosmo-engine\cosmo-engine.zip c:\projects\cosmo-engine\build\Release\cosmo_engine.exe c:\sdl_root\*

artifacts:
  - path: cosmo-engine.zip
    name: cosmo_engine
